function riegos_ds = riegos

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Volumes/GoogleDrive/My Drive/data/HortiMED DataSources/riegos.csv
%
% Auto-generated by MATLAB on 30-Nov-2021 12:12:34

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 26);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["idRegistro", "idRiego", "fechaHora", "conPH", "corrPH", "maxPH", "minPH", "valMaxPH", "valMinPH", "mediaPH", "varPH", "conCE", "corrCE", "maxCE", "minCE", "valMaxCE", "valMinCE", "mediaCE", "varCE", "horaInicio", "horaFin", "unidad", "litros", "condInicio", "condFin", "comentarios"];
opts.VariableTypes = ["double", "double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "datetime", "datetime", "categorical", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["condInicio", "condFin", "comentarios"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["unidad", "condInicio", "condFin", "comentarios"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "fechaHora", "InputFormat", "yyyy-MM-dd HH:mm:ss");
opts = setvaropts(opts, "horaInicio", "InputFormat", "yyyy-MM-dd HH:mm:ss");
opts = setvaropts(opts, "horaFin", "InputFormat", "yyyy-MM-dd HH:mm:ss");
opts = setvaropts(opts, ["conPH", "corrPH", "maxPH", "minPH", "valMaxPH", "valMinPH", "mediaPH", "varPH", "conCE", "corrCE", "valMaxCE", "valMinCE", "mediaCE", "varCE"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["conPH", "corrPH", "maxPH", "minPH", "valMaxPH", "valMinPH", "mediaPH", "varPH", "conCE", "corrCE", "valMaxCE", "valMinCE", "mediaCE", "varCE"], "ThousandsSeparator", ",");

% Import the data
riegos_ds = readtable("/Volumes/GoogleDrive/My Drive/data/HortiMED DataSources/riegos.csv", opts);


%% Clear temporary variables
