clear

%% Dowload Sysclima DataSet on XLSX Format

file = 'CS3_4_production.m';
%
file_path   = which(file);
folder_path = replace(file_path,file,'');

XLSX_path = fullfile(folder_path,'..','..','..','data/GROSS/Producción_Menaka_2021.xlsx');
%
opts = weboptions;
opts.Timeout = 25;

id = '1dParrygGINzMvShC1fdD_VTCKmY3tt5g';
websave(XLSX_path,"https://drive.google.com/u/0/uc?id="+id+"&export=download")

%% From XLSX to date
%

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/HortiMED/HortiMED-Data-Sources/data/GROSS/Producción_Menaka_2021.xlsx
%    Worksheet: Hoja1
%
% Auto-generated by MATLAB on 04-Oct-2021 10:41:07

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "Hoja1";
opts.DataRange = "A1:G101";

% Specify column names and types
opts.VariableNames = ["FechaDeEntrega", "Var2", "Var3", "Var4", "Var5", "Var6", "Bruto"];
opts.SelectedVariableNames = ["FechaDeEntrega", "Bruto"];
opts.VariableTypes = ["datetime", "char", "char", "char", "char", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "FechaDeEntrega", "InputFormat", "");

% Import the data
ProduccionMenaka2021 = readtable("/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/HortiMED/HortiMED-Data-Sources/data/GROSS/Producción_Menaka_2021.xlsx", opts, "UseExcel", false);



%%
% save
folder_path = fullfile(folder_path,'..','..','..','data/MATLAB_FORMAT/CS3_4_production.mat');

save(folder_path,'ProduccionMenaka2021')
