clear

%% Dowload Sysclima DataSet on XLSX Format

file = 'INSTALL_HortiMED_DataSources.m';
%
file_path   = which(file);
folder_path = replace(file_path,file,'');
%%
XLSX_path = fullfile(folder_path,'data/GROSS/Producción_Menaka_2021.xlsx');
%
if ~exist(XLSX_path,'file')
    opts = weboptions;
    opts.Timeout = 25;

    id = '1dParrygGINzMvShC1fdD_VTCKmY3tt5g';
    websave(XLSX_path,"https://drive.google.com/u/0/uc?id="+id+"&export=download")
end
%% From XLSX to date
%

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/HortiMED/HortiMED-Data-Sources/data/GROSS/Producción_Menaka_2021.xlsx
%    Worksheet: Hoja1
%
% Auto-generated by MATLAB on 04-Oct-2021 10:41:07

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "Hoja1";
opts.DataRange = "A1:I101";

% Specify column names and types
opts.VariableNames = ["FechaDeEntrega", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Neto"];
opts.SelectedVariableNames = ["FechaDeEntrega", "Neto"];
opts.VariableTypes = ["datetime", "char", "char", "char", "char", "char", "char", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "FechaDeEntrega", "InputFormat", "");

% Import the data
ProduccionMenaka2021 = readtable("/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/HortiMED/code/HortiMED-Data-Sources/data/GROSS/Producción_Menaka_2021.xlsx", opts, "UseExcel", false);
prod0 = ProduccionMenaka2021(2:end,:);

%% order data 
[~,ind]=sort(prod0.FechaDeEntrega);
prod1 = prod0(ind,:);

prod2 = groupsummary(prod1,'FechaDeEntrega',@sum);
prod2.Properties.VariableNames{3} = 'Neto';
%%
% clf
% hold on
% plot(prod0.FechaDeEntrega,prod0.Neto,'.-')
% plot(prod1.FechaDeEntrega,prod1.Neto,'.--')
% plot(prod2.FechaDeEntrega,prod2.Neto,'.--')
% legend
%%
% save

prod2_2020_2021 = prod2;

file_path = fullfile(folder_path,'data/MATLAB_FORMAT/CS3_4_production.mat');

save(file_path,'prod2_2020_2021')
