%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/HortiMED/code/HortiMED-Data-Sources/data/GROSS/NOIF_crop_production_2021/Sheet 1-Table 1.csv
%
% Auto-generated by MATLAB on 26-Apr-2022 10:23:26

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = [3, 13];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Aream2", "NumberOfPlants", "Density", "DateTransplanted", "GrowthPeriodFirstHarvest", "DayFirstHarvest", "EndGrowthPeriodOfHarvest", "NumberGrowDays", "system", "GreenHouse", "vegetable", "TotalYieldWeightkg", "TotalYieldWeightkgm2", "AproxNumberOfFruits", "RealYieldnumberOfFruit", "AverageTimeBetweenHarvestsdays", "FruitPerPlant", "TimesOfHarvesting", "AverageWeightPerFruitHarvestg"];
opts.VariableTypes = ["double", "double", "double", "datetime", "datetime", "double", "datetime", "double", "categorical", "double", "categorical", "double", "double", "double", "string", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "RealYieldnumberOfFruit", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["system", "vegetable", "RealYieldnumberOfFruit"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "DateTransplanted", "InputFormat", "dd/MM/yyyy");
opts = setvaropts(opts, "GrowthPeriodFirstHarvest", "InputFormat", "dd/MM/yyyy");
opts = setvaropts(opts, "EndGrowthPeriodOfHarvest", "InputFormat", "dd/MM/yyyy");
opts = setvaropts(opts, ["DayFirstHarvest", "NumberGrowDays", "GreenHouse", "AverageTimeBetweenHarvestsdays"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Aream2", "NumberOfPlants", "Density", "DayFirstHarvest", "NumberGrowDays", "GreenHouse", "TotalYieldWeightkg", "TotalYieldWeightkgm2", "AproxNumberOfFruits", "AverageTimeBetweenHarvestsdays", "FruitPerPlant", "TimesOfHarvesting", "AverageWeightPerFruitHarvestg"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["DayFirstHarvest", "NumberGrowDays", "GreenHouse", "AverageTimeBetweenHarvestsdays"], "ThousandsSeparator", ".");

% Import the data
Sheet1Table1 = readtable("/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/HortiMED/code/HortiMED-Data-Sources/data/GROSS/NOIF_crop_production_2021/Sheet 1-Table 1.csv", opts);


%% Clear temporary variables
clear opts
%% Clear temporary variables
clear opts
data = Sheet1Table1;
%% Clear temporary variables
clear opts
%%
file = 'INSTALL_HortiMED_DataSources.m';

file_path   = which(file);
folder_path = replace(file_path,file,'');

save(fullfile(folder_path,'data','MATLAB_FORMAT','CS1_4_prod.mat'),'data')